<?php
namespace ir\e\drivers;

use ir\e\drivers;

/**
 * Class Sqlite
 * 使用方式 @Sqlite?dsn=PDO DSN&table=Table Name
 * @package ir\e\drivers
 */

class Sqlite extends drivers\Db
{
    private $_db;
    protected function _init($args, $rawArgs)
    {
        //database=/21andy.com/21andy.sqlite
        parent::_init($args, $rawArgs); // TODO: Change the autogenerated stub
        $this->_db = new \PDO($args['dsn']);
    }

    /**
     * @param string $sql
     * @return array
     */
    protected function _query($sql)
    {
        //query sql
        $sth = $this->_db->prepare($sql);
        if($sth) {
            $sth->execute();
            $result = $sth->fetchAll(\PDO::FETCH_CLASS);
            return $this->_itemToArray($result);
        }
        return [];
    }

    /**
     * @param string $sql
     * @param string $sqlType
     * @return bool
     */

    protected function _exec($sql,$sqlType)
    {
        return $this->_db->exec($sql);
    }


    public function scan()
    {
        //$this->_asyncCreate();
        return parent::scan();
    }
}


