<?php
namespace ir\e\drivers;

use ir\e\App;
use ir\e\drivers;

/**
 * Class Sqlite
 * 使用方式 @Sqlite?dsn=PDO DSN&table=Table Name
 * @package ir\e\drivers
 */

class Sqlite extends drivers\Db
{
    private $_db;
    protected function _init($args, $rawArgs)
    {
        //database=/21andy.com/21andy.sqlite
        parent::_init($args, $rawArgs); // TODO: Change the autogenerated stub
        $this->_db = new \PDO($args['dsn']);
    }

    /**
     * @param string $sql
     * @return array
     */
    protected function _query($sql)
    {
        //query sql
        $sth = $this->_db->prepare($sql);
        if($sth) {
            $sth->execute();
            $result = $sth->fetchAll(\PDO::FETCH_CLASS);
            return $this->_itemToArray($result);
        }
        return [];
    }

    /**
     * @param string $sql
     * @param string $sqlType
     * @return bool
     */

    protected function _exec($sql,$sqlType)
    {
        return $this->_db->exec($sql);
    }

    //异步写入,弥补高并发写入锁死的缺陷
    public function create($data,$time){
        $data['starting_time'] = $time;
        $data['id'] = $this->_createUniqId($data);
        $f = App::getTempPath('ir-e-sqlite-create-task');

        $fCnt = file_get_contents($f);
        file_put_contents($fCnt,serialize($data),FILE_APPEND);
        return $data['id'];
    }
    private function _asyncCreate($fCnt){
        $cnt = file_get_contents($fCnt);
        $list = explode("\n",$cnt);
        foreach ($list as $_item) {
            $_item = trim($_item);
            $data = unserialize($_item);
            if (!empty($data)) {
                $id = $data['id'];
                $exist = $this->_exist($id);

                if (!$this->_exist($id)) {

                    $values = '';
                    $fields = '';
                    foreach ($data as $f => $v) {
                        $fields[] = '`' . $f . '`';
                        $values[] = var_export($v, true);
                    }
                    $fieldsStr = implode(',', $fields);
                    $valuesStr = implode(',', $values);
                    $res = $this->_exec('insert into '.$this->_table.' (' . $fieldsStr . ') values (' . $valuesStr . ')', 'insert');
                    return $res ? $id : false;

                }
            }
        }
    }


    public function scan(){
        //$this->_asyncCreate();
        return parent::scan();
    }


}


