<?php
namespace MyNamespace\event;

use ir\e\drivers;

class Driver extends drivers\Db
{
    private $_db;
    protected function _init($args, $rawArgs)
    {
        //database=/21andy.com/21andy.sqlite
        parent::_init($args, $rawArgs); // TODO: Change the autogenerated stub
        $this->_db = new PDO($args['dsn']);
        $this->_table = $args['table'];
        $this->tab_init();
    }

    /**
     * @param string $sql
     * @return array
     */
    protected function _query($sql)
    {
        //query sql
        $sth = $this->_db->prepare($sql);
        if($sth) {
            $sth->execute();
            $result = $sth->fetchAll(\PDO::FETCH_CLASS);
            if(!empty($result)){
                foreach ($result as &$v) {
                    if (is_object($v)) {
                        $v = get_object_vars($v);
                    }
                }unset($v);
            }
            return $result;
        }
        return [];
    }

    /**
     * @param string $sql
     * @param string $sqlType
     * @return bool
     */

    protected function _exec($sql,$sqlType)
    {
        return $this->_db->exec($sql);
    }
}


